name: Automation Tests

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'tags'
        required: false
        default: '@task'
        type: choice
        options:
          - '@task'

  workflow_call:
    inputs:
      tags:
        required: false
        type: string
        default: '@task'

permissions: write-all
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v1
        with:
          java-version: 23

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test Run
        working-directory: .
        run: mvn clean verify
      - name: upload test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Testreports
          path: /target/site
